name: Build

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - '**Makefile'
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build-linux:
    name: Build all
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make release
